package org.jivesoftware.sparkimpl.plugin.blucargo.registration;

public class StringConstans {

    public static String passwordSignalString ="Pole has\u0142o musi by\u0107 wype\u0142nione." ;
    public static String nameSignalString = "Pole imi\u0119 nie mo\u017ce by\u0107 puste.";
    public static String surnameSignalString = "Pole nazwisko nie mo\u017ce by\u0107 puste.";
    public static String postCdoeSignalString = "Pole kod pocztowy musi by\u0107 wype\u0142nione.";
    
    public static String[] countries(){
    	String[] tab = {
    			"-----------",
    			 "Afganistan",                                   
    			 "Albania",                                      
    			 "Algieria",                                     
    			 "Samoa Ameryka??skie",                          
    			 "Andora",                                       
    			 "Angola",                                       
    			 "Anguilla",                                     
    			 "Antarktyka",                                   
    			 "Antigua i Barbuda",                            
    			 "Argentyna",                                    
    			 "Armenia",                                      
    			 "Aruba",                                        
    			 "Australia",                                    
    			 "Austria",                                      
    			 "Azerbejd??an",                                 
    			 "Bahamy",                                       
    			 "Bahrain",                                      
    			 "Bangladesz",                                   
    			 "Barbados",                                     
    			 "Bia\u0142oru\u015b",                                   
    			 "Belgia",                                       
    			 "Belize",                                       
    			 "Benin",                                        
    			 "Bermudy",                                      
    			 "Bhutan",                                       
    			 "Boliwia",                                      
    			 "Bo\u015bnia i Hercegowina",                        
    			 "Botswana",                                     
    			 "Wyspa Bouveta",                                
    			 "Brazylia",                                     
    			 "Brytyjskie Terytorium Oceanu Indyjskiego",     
    			 "Brunei",                                       
    			 "Bu\u0142garia",                                    
    			 "Burkina Faso",                                 
    			 "Burundi",                                      
    			 "Kambod\u017ca",                                    
    			 "Kamerun",                                      
    			 "Kanada",                                       
    			 "Republika Zielonego Przyl\u0105dka",               
    			 "Kajmany",                                      
    			 "Republika \u015arodkowoafryka\u0144ska",               
    			 "Czad",                                         
    			 "Chile",                                        
    			 "Chiny",                                        
    			 "Wyspa Bo\u017cego Narodzenia",                     
    			 "Wyspy Cocos",                                  
    			 "Kolumbia",                                     
    			 "Komory",                                       
    			 "Kongo",                                        
    			 "Demokratyczna Republika Konga",                
    			 "Wyspy Cooka",                                  
    			 "Kostaryka",                                    
    			 "Wybrze??e Ko??ci S??oniowej",                  
    			 "Chorwacja",                                    
    			 "Kuba",                                         
    			 "Cypr",                                         
    			 "Czechy",                                       
    			 "Dania",                                        
    			 "D??ibutu",                                     
    			 "Dominika",                                     
    			 "Dominikana",                                   
    			 "Ekwador",                                      
    			 "Egipt",                                        
    			 "Salwador",                                     
    			 "Gwinea R??wnikowa",                            
    			 "Erytrea",                                      
    			 "Estonia",                                      
    			 "Etiopia",                                      
    			 "Falklandy Malwiny",                            
    			 "Wyspy Faraona",                                
    			 "Fid??i",                                       
    			 "Finlandia (ale nie do picia))",                
    			 "Francja",                                      
    			 "Gujana Francuska",                             
    			 "Polinezja Francuska",                          
    			 "Francuskie Terytoria Po??udniowe",             
    			 "Gabon",                                        
    			 "Gambia",                                       
    			 "Georgia Po??udniowa",                          
    			 "Niemcy",                                       
    			 "Ghana",                                        
    			 "Gibraltar",                                    
    			 "Grecja",                                       
    			 "Grenlandia",                                   
    			 "Grenada",                                      
    			 "Gwadelupa",                                    
    			 "Guam",                                         
    			 "Gwatemala",                                    
    			 "Gwinea",                                       
    			 "Gwinea Bissau",                                
    			 "Gujana",                                       
    			 "Haiti",                                        
    			 "Wyspy Heard i McDonalda",                      
    			 "Watykan",                                      
    			 "Honduras",                                     
    			 "Hong Kong",                                    
    			 "W?gry",                                        
    			 "Islandia",                                     
    			 "Indie",                                        
    			 "Indonezja",                                    
    			 "Iran",                                         
    			 "Irak",                                         
    			 "Irlandia",                                     
    			 "Izrael",                                       
    			 "W??ochy",                                      
    			 "Jamaika",                                      
    			 "Japonia",                                      
    			 "Jordania",                                     
    			 "Kazachstan",                                   
    			 "Kenia",                                        
    			 "Kiribati",                                     
    			 "Korea P????nocna",                             
    			 "Korea Po??udniowa",                            
    			 "Kuwejt",                                       
    			 "Kirgistan",                                    
    			 "Laos",                                         
    			 "???otwa",                                      
    			 "Liban",                                        
    			 "Lesotho",                                      
    			 "Liberia",                                      
    			 "Libia",                                        
    			 "Liechtenstein",                                
    			 "Litwa",                                        
    			 "Luksemburg",                                   
    			 "Makau",                                        
    			 "Macedonia",                                    
    			 "Madagaskar",                                   
    			 "Malawi",                                       
    			 "Malezja",                                      
    			 "Malediwy",                                     
    			 "Mali",                                         
    			 "Malta",                                        
    			 "Wyspy Marshalla",                              
    			 "Martynika",                                    
    			 "Mauretania",                                   
    			 "Mauritius",                                    
    			 "Majotta",                                      
    			 "Meksyk",                                       
    			 "Mikronezja",                                   
    			 "Mo??dawia",                                    
    			 "Monako",                                       
    			 "Mongolia",                                     
    			 "Montserrat",                                   
    			 "Maroko",                                       
    			 "Mozambik",                                     
    			 "Birma",                                        
    			 "Namibia",                                      
    			 "Nauru",                                        
    			 "Nepal",                                        
    			 "Holandia",                                     
    			 "Antyle Holenderskie",                          
    			 "Nowa Kaledonia",                               
    			 "Nowa Zelandia",                                
    			 "Nikaragua",                                    
    			 "Niger",                                        
    			 "Nigeria",                                      
    			 "Niue",                                         
    			 "Norfolk",                                      
    			 "Mariany P????nocne",                           
    			 "Norwegia",                                     
    			 "Oman",                                         
    			 "Pakistan",                                     
    			 "Palau",                                        
    			 "Palestyna",                                    
    			 "Panama",                                       
    			 "Papua-Nowa Gwinea",                            
    			 "Paragwaj",                                     
    			 "Peru",                                         
    			 "Filipiny",                                     
    			 "Pitcairn",                                     
    			 "Polska",                                       
    			 "Portugalia",                                   
    			 "Portoryko",                                    
    			 "Katar",                                        
    			 "Reunion",                                      
    			 "Rumunia",                                      
    			 "Rosja",                                        
    			 "Rwanda",                                       
    			 "??wi?ta Helena i Zale??ne",                    
    			 "Saint Kitts i Nevis",                          
    			 "Saint Lucia",                                  
    			 "Saint Pierre i Miquelon",                      
    			 "Saint Vincent i Grenadyny",                    
    			 "Samoa",                                        
    			 "San Marino",                                   
    			 "Wyspy ??wi?tego Tomasza i Ksi?????ca",         
    			 "Arabia Saudyjska",                             
    			 "Senegal",                                      
    			 "Czarnog??ra",                                  
    			 "Serbia",                                       
    			 "Seszele",                                      
    			 "Sierra Leone",                                 
    			 "Singapure",                                    
    			 "S??owacja",                                    
    			 "S??owenia",                                    
    			 "Wyspy Salomona",                               
    			 "Somalia",                                      
    			 "Republika Po??udniowej Afryki",                
    			 "Georgia Po??udniowa i Sandwich Po??udniowy",   
    			 "Hiszpania",                                    
    			 "Sri Lanka",                                    
    			 "Sudan",                                        
    			 "Surinam",                                      
    			 "Svalbard i Jan Mayen",                         
    			 "Suazi",                                        
    			 "Szwecja",                                      
    			 "Szwajcaria",                                   
    			 "Syria",                                        
    			 "Tajwan",                                       
    			 "Tad??ykistan",                                 
    			 "Tanzania",                                     
    			 "Tajlandia",                                    
    			 "Timor Wschodni",                               
    			 "Togo",                                         
    			 "Tokelau",                                      
    			 "Tonga",                                        
    			 "Trinidad i Tobago",                            
    			 "Tunezja",                                      
    			 "Turcja",                                       
    			 "Turkmenistan",                                 
    			 "Wyspy Turks i Caicos",                         
    			 "Tuvalu",                                       
    			 "Uganda",                                       
    			 "Ukraina",                                      
    			 "Zjednoczone Emiraty Arabskie",                 
    			 "Wielka Brytania",                              
    			 "Stany Zjednoczone",                            
    			 "Dalekie Wyspy Mniejsze Stan??w Zjednoczonych", 
    			 "Urugwaj",                                      
    			 "Uzbekistan",                                   
    			 "Vanuatu",                                      
    			 "Wenezuela",                                    
    			 "Wietnam",                                      
    			 "Brytyjskie Wyspy Dziewicze",                   
    			 "Wyspy Dziewicze Stan??w Zjednoczonych",        
    			 "Wallis i Futuna",                              
    			 "Sahara Zachodnia",                             
    			 "Jemen",                                        
    			 "Zambia",                                       
    			 "Zimbabwe"                                
    	};
    	return tab;
    }
}
