package com.blucargo.model.init;

import java.util.ArrayList;
import java.util.Date;

import com.blucargo.model.CargoOffer;
import com.blucargo.model.OfferType;


public class CreateCargoOffersData
{

    public CreateCargoOffersData()
    {
        
    }

    public ArrayList<CargoOffer> Create()
    {
            ArrayList<CargoOffer> offers=new ArrayList<CargoOffer>();
            CargoOffer co=new CargoOffer();
            co.setAddressFrom("ADR");
            co.setAddressTo("ADR");
            co.setBody("Body");
            co.setCargoPrice("100USD");
            co.setCargoOnPalette("Tak");
            co.setCashOnDelivery("Tak");
            co.setSubmissionDate(new Date());
            co.setCityFrom("Opole");
            co.setCityTo("Opole");
            co.setCountryFrom("pl");
            co.setCountryTo("pl");
            co.setDeliveryOnDay(new Date());
            co.setDescription("opis");
            co.setDimensionOfPalettes("dimension of palettes");
            co.setElevator("elevator");
            co.setHds("hds");
            co.setCargoLength("100m");
            co.setCargoLoad("100m");
            co.setLoadingDate(new Date());
            co.setNegotiable("tak");
            co.setNumberOfPalettes(100L);
            co.setOfferValid(new Date());
            co.setOtherDelivery("sdfdsf");
            co.setPartLoad("sdfsd");
            co.setPostOfficeFrom("345");
            co.setPostOfficeTo("467");
            co.setReadyToLoad("sdsdf");
            co.setStackablePalettes("tak");
            co.setUnloadingDate(new Date());
            co.setVolume("100 L");
            co.setWeight("100 T");
            co.setContact("Mir T cos tam cos tam");
            co.setOwner("b");
            co.setType(OfferType.CARGO);


            CargoOffer co1=new CargoOffer();
            co1.setAddressTo("ADR11");
            co1.setAddressFrom("ADR11");
            co1.setBody("Planteka");
            co1.setCargoPrice("100USD111");
            co1.setCargoOnPalette("Tak111");
            co1.setCashOnDelivery("Tak1111");
            co1.setSubmissionDate(new Date());
            co1.setCityFrom("Kiev");
            co1.setCityTo("Lvov");
            co1.setCountryFrom("ua");
            co1.setCountryTo("ua");
            co1.setDeliveryOnDay(new Date());
            co1.setDescription("opis1111");
            co1.setDimensionOfPalettes("dimension of palettes111");
            co1.setElevator("elevator111");
            co1.setHds("hds111");
            co1.setCargoLength("100m111");
            co1.setCargoLoad("100m111");
            co1.setLoadingDate(new Date());
            co1.setNegotiable("tak111");
            co1.setNumberOfPalettes(100L);
            co1.setOfferValid(new Date());
            co1.setOtherDelivery("sdfdsf111");
            co1.setPartLoad("sdfsd111");
            co1.setPostOfficeFrom("345111");
            co1.setPostOfficeTo("467111");
            co1.setReadyToLoad("sdsdf111");
            co1.setStackablePalettes("tak111");
            co1.setUnloadingDate(new Date());
            co1.setVolume("100 L111");
            co1.setWeight("100 T111");
            co1.setContact("Mir T cos tam cos tam111");
            co1.setOwner("b");
            co1.setType(OfferType.CARGO);

            CargoOffer co2=new CargoOffer();
            co2.setAddressTo("ADR2222");
            co2.setAddressFrom("ADR2222");
            co2.setBody("IZO");
            co2.setCargoPrice("100USD222");
            co2.setCargoOnPalette("Tak222");
            co2.setCashOnDelivery("Tak222");
            co2.setSubmissionDate(new Date());
            co2.setCityFrom("London");
            co2.setCityTo("birmingham");
            co2.setCountryFrom("uk");
            co2.setCountryTo("uk");
            co2.setDeliveryOnDay(new Date());
            co2.setDescription("opis2222");
            co2.setDimensionOfPalettes("dimension of palettes222");
            co2.setElevator("elevator2222");
            co2.setHds("hds222");
            co2.setCargoLength("100m222");
            co2.setCargoLoad("100m222");
            co2.setLoadingDate(new Date());
            co2.setNegotiable("tak222");
            co2.setNumberOfPalettes(100L);
            co2.setOfferValid(new Date());
            co2.setOtherDelivery("sdfdsf222");
            co2.setPartLoad("sdfsd2222");
            co2.setPostOfficeFrom("345222");
            co2.setPostOfficeTo("467222");
            co2.setReadyToLoad("sdsdf222");
            co2.setStackablePalettes("tak222");
            co2.setUnloadingDate(new Date());
            co2.setVolume("100 L222");
            co2.setWeight("100 T222");
            co2.setContact("Mir T cos tam cos tam222");
            co2.setOwner("b");
            co2.setType(OfferType.VEHICLE);

            CargoOffer co3=new CargoOffer();
            co3.setAddressTo("ADR333");
            co3.setAddressFrom("ADR333");
            co3.setBody("ASDAD");
            co3.setCargoPrice("100USD333");
            co3.setCargoOnPalette("Tak333");
            co3.setCashOnDelivery("Tak333");
            co3.setSubmissionDate(new Date());
            co3.setCityFrom("Warszawa");
            co3.setCityTo("Rzesz�w");
            co3.setCountryFrom("pl");
            co3.setCountryTo("pl");
            co3.setDeliveryOnDay(new Date());
            co3.setDescription("opis333");
            co3.setDimensionOfPalettes("dimension of palettes3333");
            co3.setElevator("elevator333");
            co3.setHds("hds333");
            co3.setCargoLength("100m333");
            co3.setCargoLoad("100m333");
            co3.setLoadingDate(new Date());
            co3.setNegotiable("tak333");
            co3.setNumberOfPalettes(100L);
            co3.setOfferValid(new Date());
            co3.setOtherDelivery("sdfdsf333");
            co3.setPartLoad("sdfsd333");
            co3.setPostOfficeFrom("345333");
            co3.setPostOfficeTo("4673333");
            co3.setReadyToLoad("sdsdf333");
            co3.setStackablePalettes("tak333");
            co3.setUnloadingDate(new Date());
            co3.setVolume("100 L333");
            co3.setWeight("100 T3333");
            co3.setContact("Mir T cos tam cos tam333");
            co3.setOwner("b");
            co3.setType(OfferType.VEHICLE);

            CargoOffer co4=new CargoOffer();
            co4.setAddressTo("dsddsf");
            co4.setAddressFrom("dsddsf");
            co4.setBody("sdfaaaa");
            co4.setCargoPrice("100USD444");
            co4.setCargoOnPalette("Tak444");
            co4.setCashOnDelivery("Tak444");
            co4.setSubmissionDate(new Date());
            co4.setCityFrom("Bakar");
            co4.setCityTo("Barban");
            co4.setCountryFrom("kr");
            co4.setCountryTo("kr");
            co4.setDeliveryOnDay(new Date());
            co4.setDescription("opis4444");
            co4.setDimensionOfPalettes("dimension of palettes4444");
            co4.setElevator("elevator444");
            co4.setHds("hds444");
            co4.setCargoLength("100m44");
            co4.setCargoLoad("100m44");
            co4.setLoadingDate(new Date());
            co4.setNegotiable("tak44");
            co4.setNumberOfPalettes(100L);
            co4.setOfferValid(new Date());
            co4.setOtherDelivery("sdfdsf44");
            co4.setPartLoad("sdfsd444");
            co4.setPostOfficeFrom("345444");
            co4.setPostOfficeTo("467444");
            co4.setReadyToLoad("sdsdf");
            co4.setStackablePalettes("tak444");
            co4.setUnloadingDate(new Date());
            co4.setVolume("100 L444");
            co4.setWeight("100 T444");
            co4.setContact("Mir T cos tam cos tam444");
            co4.setOwner("b");
            co4.setType(OfferType.VEHICLE);

            CargoOffer co5=new CargoOffer();
            co5.setAddressTo("dsddsf");
            co5.setAddressFrom("dsddsf");
            co5.setBody("plandeka");
            co5.setCargoPrice("100USD444");
            co5.setCargoOnPalette("Tak444");
            co5.setCashOnDelivery("Tak444");
            co5.setSubmissionDate(new Date());
            co5.setCityFrom("Opole");
            co5.setCityTo("Krak�w");
            co5.setCountryFrom("pl");
            co5.setCountryTo("pl");
            co5.setDeliveryOnDay(new Date());
            co5.setDescription("opis4444");
            co5.setDimensionOfPalettes("dimension of palettes4444");
            co5.setElevator("elevator444");
            co5.setHds("hds444");
            co5.setCargoLength("100m44");
            co5.setCargoLoad("100m44");
            co5.setLoadingDate(new Date());
            co5.setNegotiable("tak44");
            co5.setNumberOfPalettes(100L);
            co5.setOfferValid(new Date());
            co5.setOtherDelivery("sdfdsf44");
            co5.setPartLoad("sdfsd444");
            co5.setPostOfficeFrom("345444");
            co5.setPostOfficeTo("467444");
            co5.setReadyToLoad("sdsdf");
            co5.setStackablePalettes("tak444");
            co5.setUnloadingDate(new Date());
            co5.setVolume("100 L444");
            co5.setWeight("k1");
            co5.setContact("Mir T cos tam cos tam444");
            co5.setOwner("b");
            co5.setType(OfferType.VEHICLE);

            CargoOffer co6=new CargoOffer();
            co6.setAddressTo("dsddsf");
            co6.setAddressFrom("dsddsf");
            co6.setBody("izoterma");
            co6.setCargoPrice("100USD444");
            co6.setCargoOnPalette("Tak444");
            co6.setCashOnDelivery("Tak444");
            co6.setSubmissionDate(new Date());
            co6.setCityFrom("Opole");
            co6.setCityTo("moskva");
            co6.setCountryFrom("pl");
            co6.setCountryTo("ru");
            co6.setDeliveryOnDay(new Date());
            co6.setDescription("opis4444");
            co6.setDimensionOfPalettes("dimension of palettes4444");
            co6.setElevator("elevator444");
            co6.setHds("hds444");
            co6.setCargoLength("100m44");
            co6.setCargoLoad("100m44");
            co6.setLoadingDate(new Date());
            co6.setNegotiable("tak44");
            co6.setNumberOfPalettes(100L);
            co6.setOfferValid(new Date());
            co6.setOtherDelivery("sdfdsf44");
            co6.setPartLoad("sdfsd444");
            co6.setPostOfficeFrom("345444");
            co6.setPostOfficeTo("467444");
            co6.setReadyToLoad("sdsdf");
            co6.setStackablePalettes("tak444");
            co6.setUnloadingDate(new Date());
            co6.setVolume("100 L444");
            co6.setWeight("k2");
            co6.setContact("Mir T cos tam cos tam444");
            co6.setOwner("b");
            co6.setType(OfferType.VEHICLE);

            CargoOffer co7=new CargoOffer();
            co7.setAddressTo("dsddsf");
            co7.setAddressFrom("dsddsf");
            co7.setBody("izoterma");
            co7.setCargoPrice("100USD444");
            co7.setCargoOnPalette("Tak444");
            co7.setCashOnDelivery("Tak444");
            co7.setSubmissionDate(new Date());
            co7.setCityFrom("desinic");
            co7.setCityTo("moskva");
            co7.setCountryFrom("kr");
            co7.setCountryTo("ru");
            co7.setDeliveryOnDay(new Date());
            co7.setDescription("opis4444");
            co7.setDimensionOfPalettes("dimension of palettes4444");
            co7.setElevator("elevator444");
            co7.setHds("hds444");
            co7.setCargoLength("100m44");
            co7.setCargoLoad("100m44");
            co7.setLoadingDate(new Date());
            co7.setNegotiable("tak44");
            co7.setNumberOfPalettes(100L);
            co7.setOfferValid(new Date());
            co7.setOtherDelivery("sdfdsf44");
            co7.setPartLoad("sdfsd444");
            co7.setPostOfficeFrom("345444");
            co7.setPostOfficeTo("467444");
            co7.setReadyToLoad("sdsdf");
            co7.setStackablePalettes("tak444");
            co7.setUnloadingDate(new Date());
            co7.setVolume("100 L444");
            co7.setWeight("k2");
            co7.setContact("Mir T cos tam cos tam444");
            co7.setOwner("b");
            co7.setType(OfferType.VEHICLE);

            offers.add(co);
            offers.add(co1);
            offers.add(co2);
            offers.add(co3);
            offers.add(co4);
            offers.add(co5);
            offers.add(co6);

            return offers;
    }

}
