/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.blucargo.model.init;

import java.util.ArrayList;

import com.blucargo.model.Country;


/**
 *
 * @author kadet
 */
public class CreateCountriesData {
    public ArrayList<Country> Create()
    {
            ArrayList<Country> countries=new ArrayList<Country>();
            countries.add(new Country("AF","AFGANISTAN","Afganistan","AFG","004"));
            countries.add(new Country("AL","ALBANIA","Albania","ALB","008"));
            countries.add(new Country("DZ","ALGIERIA","Algieria","DZA","012"));
            countries.add(new Country("AS","SAMOA AMERYKAÑSKIE","Samoa Amerykañskie","ASM","016"));
            countries.add(new Country("AD","ANDORA","Andora","AND","020"));
            countries.add(new Country("AO","ANGOLA","Angola","AGO","024"));
            countries.add(new Country("AI","ANGUILLA","Anguilla","AIA","660"));
            countries.add(new Country("AQ","ANTARKTYKA","Antarktyka",null,null));
            countries.add(new Country("AG","ANTIGUA I BARBUDA","Antigua i Barbuda","ATG","028"));
            countries.add(new Country("AR","ARGENTYNA","Argentyna","ARG","032"));
            countries.add(new Country("AM","ARMENIA","Armenia","ARM","051"));
            countries.add(new Country("AW","ARUBA","Aruba","ABW","533"));
            countries.add(new Country("AU","AUSTRALIA","Australia","AUS","036"));
            countries.add(new Country("AT","AUSTRIA","Austria","AUT","040"));
            countries.add(new Country("AZ","AZERBEJD¯AN","Azerbejd¿an","AZE","031"));
            countries.add(new Country("BS","BAHAMY","Bahamy","BHS","044"));
            countries.add(new Country("BH","BAHRAIN","Bahrain","BHR","048"));
            countries.add(new Country("BD","BANGLADESZ","Bangladesz","BGD","050"));
            countries.add(new Country("BB","BARBADOS","Barbados","BRB","052"));
            countries.add(new Country("BY","BIAłORUŚ","Bia³oruŚ","BLR","112"));
            countries.add(new Country("BE","BELGIA","Belgia","BEL","056"));
            countries.add(new Country("BZ","BELIZE","Belize","BLZ","084"));
            countries.add(new Country("BJ","BENIN","Benin","BEN","204"));
            countries.add(new Country("BM","BERMUDY","Bermudy","BMU","060"));
            countries.add(new Country("BT","BHUTAN","Bhutan","BTN","064"));
            countries.add(new Country("BO","BOLIWIA","Boliwia","BOL","068"));
            countries.add(new Country("BA","BOŚNIA I HERCEGOWINA","BoŚnia i Hercegowina","BIH","070"));
            countries.add(new Country("BW","BOTSWANA","Botswana","BWA","072"));
            countries.add(new Country("BV","WYSPA BOUVETA","Wyspa Bouveta",null,null));
            countries.add(new Country("BR","BRAZYLIA","Brazylia","BRA","076"));
            countries.add(new Country("IO","BRYTYJSKIE TERYTORIUM OCEANU INDYJSKIEGO","Brytyjskie Terytorium Oceanu Indyjskiego",null,null));
            countries.add(new Country("BN","BRUNEI","Brunei","BRN","096"));
            countries.add(new Country("BG","BUłGARIA","Bu³garia","BGR","100"));
            countries.add(new Country("BF","BURKINA FASO","Burkina Faso","BFA","854"));
            countries.add(new Country("BI","BURUNDI","Burundi","BDI","108"));
            countries.add(new Country("KH","KAMBOD¯A","Kambod¿a","KHM","116"));
            countries.add(new Country("CM","KAMERUN","Kamerun","CMR","120"));
            countries.add(new Country("CA","KANADA","Kanada","CAN","124"));
            countries.add(new Country("CV","REPUBLIKA ZIELONEGO PRZYL¥DKA","Republika Zielonego Przyl¹dka","CPV","132"));
            countries.add(new Country("KY","KAJMANY","Kajmany","CYM","136"));
            countries.add(new Country("CF","REPUBLIKA ŚRODKOWOAFRYKAÑSKA","Republika Środkowoafrykañska","CAF","140"));
            countries.add(new Country("TD","CZAD","Czad","TCD","148"));
            countries.add(new Country("CL","CHILE","Chile","CHL","152"));
            countries.add(new Country("CN","CHINY","Chiny","CHN","156"));
            countries.add(new Country("CX","WYSPA BO¯EGO NARODZENIA","Wyspa Bo¿ego Narodzenia",null,null));
            countries.add(new Country("CC","WYSPY COCOS","Wyspy Cocos",null,null));
            countries.add(new Country("CO","KOLUMBIA","Kolumbia","COL","170"));
            countries.add(new Country("KM","KOMORY","Komory","COM","174"));
            countries.add(new Country("CG","KONGO","Kongo","COG","178"));
            countries.add(new Country("CD","DEMOKRATYCZNA REPUBLIKA KONGA","Demokratyczna Republika Konga","COD","180"));
            countries.add(new Country("CK","WYSPY COOKA","Wyspy Cooka","COK","184"));
            countries.add(new Country("CR","KOSTARYKA","Kostaryka","CRI","188"));
            countries.add(new Country("CI","WYBRZE¯E KOŚCI SłONIOWEJ","Wybrze¿e KoŚci S³oniowej","CIV","384"));
            countries.add(new Country("HR","CHORWACJA","Chorwacja","HRV","191"));
            countries.add(new Country("CU","KUBA","Kuba","CUB","192"));
            countries.add(new Country("CY","Cypr","Cypr","CYP","196"));
            countries.add(new Country("CZ","CZECHY","Czechy","CZE","203"));
            countries.add(new Country("DK","DANIA","Dania","DNK","208"));
            countries.add(new Country("DJ","D¯IBUTI","D¿ibutu","DJI","262"));
            countries.add(new Country("DM","DOMINIKA","Dominika","DMA","212"));
            countries.add(new Country("DO","DOMINIKANA","Dominikana","DOM","214"));
            countries.add(new Country("EC","EKWADOR","Ekwador","ECU","218"));
            countries.add(new Country("EG","EGIPT","Egipt","EGY","818"));
            countries.add(new Country("SV","SALWADOR","Salwador","SLV","222"));
            countries.add(new Country("GQ","GWINEA RÓWNIKOWA","Gwinea Równikowa","GNQ","226"));
            countries.add(new Country("ER","ERyTREA","Erytrea","ERI","232"));
            countries.add(new Country("EE","ESTONIA","Estonia","EST","233"));
            countries.add(new Country("ET","ETIOPIA","Etiopia","ETH","231"));
            countries.add(new Country("FK","FALKLANDY MALWINY","Falklandy Malwiny","FLK","238"));
            countries.add(new Country("FO","WYSPY FARAONA","Wyspy Faraona","FRO","234"));
            countries.add(new Country("FJ","FID¯I","Fid¿i","FJI","242"));
            countries.add(new Country("FI","FINLANDIA","Finlandia (ale nie do picia))","FIN","246"));
            countries.add(new Country("FR","FRANCJA","Francja","FRA","250"));
            countries.add(new Country("GF","GRUJANA FRANCUSKA","Gujana Francuska","GUF","254"));
            countries.add(new Country("PF","POLINEZJA FRANCUSKA","Polinezja Francuska","PYF","258"));
            countries.add(new Country("TF","FRANCUSKIE TERYTORIA POłUDNIOWE","Francuskie Terytoria Po³udniowe",null,null));
            countries.add(new Country("GA","GABON","Gabon","GAB","266"));
            countries.add(new Country("GM","GAMBIA","Gambia","GMB","270"));
            countries.add(new Country("GE","GEORGIA POłUDNIOWA","Georgia Po³udniowa","GEO","268"));
            countries.add(new Country("DE","NIEMCY","Niemcy","DEU","276"));
            countries.add(new Country("GH","GHANA","Ghana","GHA","288"));
            countries.add(new Country("GI","GIBRALTAR","Gibraltar","GIB","292"));
            countries.add(new Country("GR","GRECJA","Grecja","GRC","300"));
            countries.add(new Country("GL","GRENLANDIA","Grenlandia","GRL","304"));
            countries.add(new Country("GD","GRENADA","Grenada","GRD","308"));
            countries.add(new Country("GP","GWADELUPA","Gwadelupa","GLP","312"));
            countries.add(new Country("GU","GUAM","Guam","GUM","316"));
            countries.add(new Country("GT","GWATEMALA","Gwatemala","GTM","320"));
            countries.add(new Country("GN","GWINEA","Gwinea","GIN","324"));
            countries.add(new Country("GW","GWINEA-BISSAU","Gwinea Bissau","GNB","624"));
            countries.add(new Country("GY","GUJANA","Gujana","GUY","328"));
            countries.add(new Country("HT","HAITI","Haiti","HTI","332"));
            countries.add(new Country("HM","WYSPY HEARD I MCDONALDA","Wyspy Heard i McDonalda",null,null));
            countries.add(new Country("VA","WATYKAN","Watykan","VAT","336"));
            countries.add(new Country("HN","HONDURAS","Honduras","HND","340"));
            countries.add(new Country("HK","HONG KONG","Hong Kong","HKG","344"));
            countries.add(new Country("HU","WęGRY","Węgry","HUN","348"));
            countries.add(new Country("IS","ISLANDIA","Islandia","ISL","352"));
            countries.add(new Country("IN","INDIE","Indie","IND","356"));
            countries.add(new Country("ID","INDONEZJA","Indonezja","IDN","360"));
            countries.add(new Country("IR","IRAN","Iran","IRN","364"));
            countries.add(new Country("IQ","IRAK","Irak","IRQ","368"));
            countries.add(new Country("IE","IRLANDIA","Irlandia","IRL","372"));
            countries.add(new Country("IL","IZRAEL","Izrael","ISR","376"));
            countries.add(new Country("IT","WłOCHY","W³ochy","ITA","380"));
            countries.add(new Country("JM","JAMAIKA","Jamaika","JAM","388"));
            countries.add(new Country("JP","JAPONIA","Japonia","JPN","392"));
            countries.add(new Country("JO","JORDANIA","Jordania","JOR","400"));
            countries.add(new Country("KZ","KAZACHSTAN","Kazachstan","KAZ","398"));
            countries.add(new Country("KE","KENIA","Kenia","KEN","404"));
            countries.add(new Country("KI","KIRIBATI","Kiribati","KIR","296"));
            countries.add(new Country("KP","KOREA PÓłNOCNA","Korea Pó³nocna","PRK","408"));
            countries.add(new Country("KR","KOREA POłUDNIOWA","Korea Po³udniowa","KOR","410"));
            countries.add(new Country("KW","KUWEJT","Kuwejt","KWT","414"));
            countries.add(new Country("KG","KIRGISTAN","Kirgistan","KGZ","417"));
            countries.add(new Country("LA","LAOS","Laos","LAO","418"));
            countries.add(new Country("LV","�OTWA","�otwa","LVA","428"));
            countries.add(new Country("LB","LIBAN","Liban","LBN","422"));
            countries.add(new Country("LS","LESOTHO","Lesotho","LSO","426"));
            countries.add(new Country("LR","LIBERIA","Liberia","LBR","430"));
            countries.add(new Country("LY","LIBIA","Libia","LBY","434"));
            countries.add(new Country("LI","LIECHTENSTEIN","Liechtenstein","LIE","438"));
            countries.add(new Country("LT","LITWA","Litwa","LTU","440"));
            countries.add(new Country("LU","LUKSEMBURG","Luksemburg","LUX","442"));
            countries.add(new Country("MO","MAKAU","Makau","MAC","446"));
            countries.add(new Country("MK","MACEDONIA","Macedonia","MKD","807"));
            countries.add(new Country("MG","MADAGASkAR","Madagaskar","MDG","450"));
            countries.add(new Country("MW","MALAWI","Malawi","MWI","454"));
            countries.add(new Country("MY","MALEZJA","Malezja","MYS","458"));
            countries.add(new Country("MV","MALEDIWY","Malediwy","MDV","462"));
            countries.add(new Country("ML","MALI","Mali","MLI","466"));
            countries.add(new Country("MT","MALTA","Malta","MLT","470"));
            countries.add(new Country("MH","WYSPY MARSHALLA","Wyspy Marshalla","MHL","584"));
            countries.add(new Country("MQ","MARTYNIKA","Martynika","MTQ","474"));
            countries.add(new Country("MR","MAURETANIA","Mauretania","MRT","478"));
            countries.add(new Country("MU","MAURITIUS","Mauritius","MUS","480"));
            countries.add(new Country("YT","MAJOTTA","Majotta",null,null));
            countries.add(new Country("MX","MEKSYK","Meksyk","MEX","484"));
            countries.add(new Country("FM","MIKRONEZJA","Mikronezja","FSM","583"));
            countries.add(new Country("MD","MOłDAWIA","Mo³dawia","MDA","498"));
            countries.add(new Country("MC","MONAKO","Monako","MCO","492"));
            countries.add(new Country("MN","MONGOLIA","Mongolia","MNG","496"));
            countries.add(new Country("MS","MONTSERRAT","Montserrat","MSR","500"));
            countries.add(new Country("MA","MAROKO","Maroko","MAR","504"));
            countries.add(new Country("MZ","MOZAMBIK","Mozambik","MOZ","508"));
            countries.add(new Country("MM","BIRMA","Birma","MMR","104"));
            countries.add(new Country("NA","NAMIBIA","Namibia","NAM","516"));
            countries.add(new Country("NR","NAURU","Nauru","NRU","520"));
            countries.add(new Country("NP","NEPAL","Nepal","NPL","524"));
            countries.add(new Country("NL","HOLANDIA","Holandia","NLD","528"));
            countries.add(new Country("AN","ANTYLE HOLENDERSKIE","Antyle Holenderskie","ANT","530"));
            countries.add(new Country("NC","NOWA KALEDONIA","Nowa Kaledonia","NCL","540"));
            countries.add(new Country("NZ","NOWA ZELANDIA","Nowa Zelandia","NZL","554"));
            countries.add(new Country("NI","NIKARAGUA","Nikaragua","NIC","558"));
            countries.add(new Country("NE","NIGER","Niger","NER","562"));
            countries.add(new Country("NG","NIGERIA","Nigeria","NGA","566"));
            countries.add(new Country("NU","NIUE","Niue","NIU","570"));
            countries.add(new Country("NF","NORFOLK","Norfolk","NFK","574"));
            countries.add(new Country("MP","MARIANY PÓłNOCNE","Mariany Pó³nocne","MNP","580"));
            countries.add(new Country("NO","NORWEGIA","Norwegia","NOR","578"));
            countries.add(new Country("OM","OMAN","Oman","OMN","512"));
            countries.add(new Country("PK","PAKISTAN","Pakistan","PAK","586"));
            countries.add(new Country("PW","PALAU","Palau","PLW","585"));
            countries.add(new Country("PS","PALESTYNA","Palestyna",null,null));
            countries.add(new Country("PA","PANAMA","Panama","PAN","591"));
            countries.add(new Country("PG","PAPUA-NOWA GWINEA","Papua-Nowa Gwinea","PNG","598"));
            countries.add(new Country("PY","PARAGWAJ","Paragwaj","PRY","600"));
            countries.add(new Country("PE","PERU","Peru","PER","604"));
            countries.add(new Country("PH","FILIPINY","Filipiny","PHL","608"));
            countries.add(new Country("PN","PITCAIRN","Pitcairn","PCN","612"));
            countries.add(new Country("PL","POLSKA","Polska","POL","616"));
            countries.add(new Country("PT","PORTUGALIA","Portugalia","PRT","620"));
            countries.add(new Country("PR","PORTORYKO","Portoryko","PRI","630"));
            countries.add(new Country("QA","KATAR","Katar","QAT","634"));
            countries.add(new Country("RE","REUNION","Reunion","REU","638"));
            countries.add(new Country("RO","RUMUNIA","Rumunia","ROM","642"));
            countries.add(new Country("RU","ROSJA","Rosja","RUS","643"));
            countries.add(new Country("RW","RWANDA","Rwanda","RWA","646"));
            countries.add(new Country("SH","ŚWIęTA HELENA","Święta Helena i Zale¿ne","SHN","654"));
            countries.add(new Country("KN","SAINT KITTS I NEVIS","Saint Kitts i Nevis","KNA","659"));
            countries.add(new Country("LC","SAINT LUCIA","Saint Lucia","LCA","662"));
            countries.add(new Country("PM","SAINT PIERRE I MIQUELON","Saint Pierre i Miquelon","SPM","666"));
            countries.add(new Country("VC","SAINT VINCENT I GRENADYNY","Saint Vincent i Grenadyny","VCT","670"));
            countries.add(new Country("WS","SAMOA","Samoa","WSM","882"));
            countries.add(new Country("SM","SAN MARINO","San Marino","SMR","674"));
            countries.add(new Country("ST","WYSPY ŚWIęTEGO TOMASZA I KSI¥¯ęCA","Wyspy Świętego Tomasza i Ksi¹¿ęca","STP","678"));
            countries.add(new Country("SA","ARABIA SAUDYJSKA","Arabia Saudyjska","SAU","682"));
            countries.add(new Country("SN","SENEGAL","Senegal","SEN","686"));
            countries.add(new Country("ME","CZARNOGÓRA","Czarnogóra","MNE","499"));
            countries.add(new Country("RS","SERBIA","Serbia","SRB","688"));
            countries.add(new Country("SC","SESZELE","Seszele","SYC","690"));
            countries.add(new Country("SL","SIERRA LEONE","Sierra Leone","SLE","694"));
            countries.add(new Country("SG","SINGAPURE","Singapure","SGP","702"));
            countries.add(new Country("SK","SłOWACJA","S³owacja","SVK","703"));
            countries.add(new Country("SI","SłOWENIA","S³owenia","SVN","705"));
            countries.add(new Country("SB","WYSPY SALOMONA","Wyspy Salomona","SLB","090"));
            countries.add(new Country("SO","SOMALIA","Somalia","SOM","706"));
            countries.add(new Country("ZA","REPUBLIKA POłUDNIOWEJ AFRYKI","Republika Po³udniowej Afryki","ZAF","710"));
            countries.add(new Country("GS","GEORGIA POłUDNIOWA I SANDWICH POłUDNIOWY","Georgia Po³udniowa i Sandwich Po³udniowy",null,null));
            countries.add(new Country("ES","HISZPANIA","Hiszpania","ESP","724"));
            countries.add(new Country("LK","SRI LANKA","Sri Lanka","LKA","144"));
            countries.add(new Country("SD","SUDAN","Sudan","SDN","736"));
            countries.add(new Country("SR","SURINAM","Surinam","SUR","740"));
            countries.add(new Country("SJ","SVALBARD I JAN MAYEN","Svalbard i Jan Mayen","SJM","744"));
            countries.add(new Country("SZ","SUAZI","Suazi","SWZ","748"));
            countries.add(new Country("SE","SZWECJA","Szwecja","SWE","752"));
            countries.add(new Country("CH","SZWAJCARIA","Szwajcaria","CHE","756"));
            countries.add(new Country("SY","SYRIA","Syria","SYR","760"));
            countries.add(new Country("TW","TAJWAN","Tajwan","TWN","158"));
            countries.add(new Country("TJ","TAD¯YKISTAN","Tad¿ykistan","TJK","762"));
            countries.add(new Country("TZ","TANZANIA","Tanzania","TZA","834"));
            countries.add(new Country("TH","TAJLANDIA","Tajlandia","THA","764"));
            countries.add(new Country("TL","TIMOR WSCHODNI","Timor Wschodni",null,null));
            countries.add(new Country("TG","TOGO","Togo","TGO","768"));
            countries.add(new Country("TK","TOKELAU","Tokelau","TKL","772"));
            countries.add(new Country("TO","TONGA","Tonga","TON","776"));
            countries.add(new Country("TT","TRINIDAD I TOBAGO","Trinidad i Tobago","TTO","780"));
            countries.add(new Country("TN","TUNEZJA","Tunezja","TUN","788"));
            countries.add(new Country("TR","TURCJA","Turcja","TUR","792"));
            countries.add(new Country("TM","TURKMENISTAN","Turkmenistan","TKM","795"));
            countries.add(new Country("TC","WYSPY TURKS I CAICOS","Wyspy Turks i Caicos","TCA","796"));
            countries.add(new Country("TV","TUVALU","Tuvalu","TUV","798"));
            countries.add(new Country("UG","UGANDA","Uganda","UGA","800"));
            countries.add(new Country("UA","UKRAINA","Ukraina","UKR","804"));
            countries.add(new Country("AE","ZJEDNOCZONE EMIRATY ARABSKIE","Zjednoczone Emiraty Arabskie","ARE","784"));
            countries.add(new Country("GB","WIELKA BRYTANIA","Wielka Brytania","GBR","826"));
            countries.add(new Country("US","STANY ZJEDNOCZONE","Stany Zjednoczone","USA","840"));
            countries.add(new Country("UM","DALEKIE WYSPY MNIEJSZE STANÓW ZJEDNOCZONYCH","Dalekie Wyspy Mniejsze Stanów Zjednoczonych",null,null));
            countries.add(new Country("UY","URUGWAJ","Urugwaj","URY","858"));
            countries.add(new Country("UZ","UZBEKISTAN","Uzbekistan","UZB","860"));
            countries.add(new Country("VU","VANUATU","Vanuatu","VUT","548"));
            countries.add(new Country("VE","WENEZUELA","Wenezuela","VEN","862"));
            countries.add(new Country("VN","WIETNAM","Wietnam","VNM","704"));
            countries.add(new Country("VG","BRYTYJSKIE WYSPY DZIEWICZE","Brytyjskie Wyspy Dziewicze","VGB","092"));
            countries.add(new Country("VI","WYSPY DZIEWICZE STANÓW ZJEDNOCZONYCH","Wyspy Dziewicze Stanów Zjednoczonych","VIR","850"));
            countries.add(new Country("WF","WALLIS I FUTUNA","Wallis i Futuna","WLF","876"));
            countries.add(new Country("EH","SAHARA ZACHODNIA","Sahara Zachodnia","ESH","732"));
            countries.add(new Country("YE","JEMEN","Jemen","YEM","887"));
            countries.add(new Country("ZM","ZAMBIA","Zambia","ZMB","894"));
            countries.add(new Country("ZW","ZIMBABWE","Zimbabwe","ZWE","716"));

            return countries;
    }

}
